# These are supported funding model platforms

github: shakaran
open_collective: shakaran
ko_fi: shakaran
custom: ["https://www.paypal.me/shakaran", "https://ko-fi.com/shakaran", "https://wise.com/pay/me/angelg1148"]
